"""Routing on the benchmark's human labels: withhold the opinions a detector ranks highest.

The benchmark's GPT-4 opinions with their human hallucination label, scored out-of-fold by the
in-domain probe (data/publichearingbr/probe_scores_llama_31_8b_instruct.jsonl, written by
run_publichearingbr_probe.py) and by the lexical referee of the generation runs (1 - content-word
containment in the best of the opinion's four chunks). For each operating point (top 2, 5, 10, 20,
30% by score): share withheld, unsupported opinions removed (Wilson 95% CI), unsupported kept,
supported opinions lost, and the unsupported rate among the opinions kept. withhold_curve() is also
used by routing_fresh.py.

Usage: uv run python scripts/mitigation_headroom.py
Writes data/publichearingbr/routing_benchmark.md. CPU only.
"""
import json
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
from synth3_results import auc  # noqa: E402

from attribution_generation import containment  # noqa: E402

from ocarandu.data.publichearingbr import load_nli_opinions  # noqa: E402


def wilson(k, n):
    if not n:
        return (float("nan"), float("nan"))
    p, z = k / n, 1.959964
    d = 1 + z * z / n
    c = (p + z * z / (2 * n)) / d
    h = z * np.sqrt(p * (1 - p) / n + z * z / (4 * n * n)) / d
    return (max(0.0, c - h), min(1.0, c + h))


def withhold_curve(scores, y, name, L):
    """Drop the top-q share by `scores`; report what is removed and what it costs."""
    s, y = np.asarray(scores, float), np.asarray(y, int)
    m = ~np.isnan(s)
    s, y = s[m], y[m]
    if y.sum() == 0:
        L.append(f"| {name} | — | no positives | | | |")
        return
    L.append(f"| **{name}** (n={len(y)}, {int(y.sum())} unsupported, AUC {auc(s, y):.3f}) | | | | | |")
    for q in (0.02, 0.05, 0.10, 0.20, 0.30):
        thr = np.quantile(s, 1 - q)
        flag = s >= thr
        caught, kept_bad = int((flag & (y == 1)).sum()), int((~flag & (y == 1)).sum())
        lost_good = int((flag & (y == 0)).sum())
        lo, hi = wilson(caught, int(y.sum()))
        L.append(f"| withhold top {q:.0%} | {flag.mean():.3f} | {caught}/{int(y.sum())} "
                 f"({caught / y.sum():.2f}, 95% CI {lo:.2f}–{hi:.2f}) | {kept_bad} | {lost_good} "
                 f"({lost_good / max(1, (y == 0).sum()):.1%} of supported) | {(kept_bad / max(1, (~flag).sum())):.4f} |")


def main():
    sc = ROOT / "data" / "publichearingbr" / "probe_scores_llama_31_8b_instruct.jsonl"
    rs = [json.loads(line) for line in open(sc, encoding="utf-8")]
    y = [int(r["label"]) for r in rs]
    L = ["# Routing on the benchmark's human labels", "",
         f"{len(rs)} GPT-4 opinions with the benchmark's human label, Llama-3.1 in-domain probe out-of-fold. "
         "Generated by `scripts/mitigation_headroom.py`.", "",
         "| operating point | share withheld | unsupported removed | unsupported kept | supported lost | residual rate |",
         "|---|---:|---:|---:|---:|---:|"]
    withhold_curve([r["proba"] for r in rs], y, f"in-domain probe (L{rs[0]['layer']})", L)
    chunks = {(o.sample_id, o.opinion.strip()): list(o.context_chunks) for o in load_nli_opinions()}
    lex = [1 - containment(r["opinion"], chunks.get((r["sample_id"], r["opinion"].strip()), []))
           if (r["sample_id"], r["opinion"].strip()) in chunks else np.nan for r in rs]
    withhold_curve(lex, y, "lexical referee (content-word containment)", L)
    text = "\n".join(L) + "\n"
    (ROOT / "data" / "publichearingbr" / "routing_benchmark.md").write_text(text, encoding="utf-8")
    print(text)


if __name__ == "__main__":
    main()
