"""Detect-and-route on the model's own generations, against blind rater labels.

Uses the baseline arm of the blind round synth3_gcad500 (Llama-3.1, cross-fit fold A,
replicated blocks excluded). Detectors: lexical referee (1 - containment), residual
probe (p14 in probe_fresh/llama_31_8b_instruct/scores.csv) and NLI cross-encoder
(nli_verifier/corruptions_llama_31_8b_instruct.csv). For each, the top-q flagged opinions
are withheld and the table reports how many of the rater-flagged unsupported opinions are
caught and at what cost, at the opinion level and at the participant level (participants
whose summary still carries one).
Scores are joined on (sample_id, speaker, opinion_idx), which assumes the round's
baseline text is identical to the llama_31_8b_instruct_lc_xfitA baseline they were
computed on.

Usage: uv run python scripts/routing_fresh.py
Writes data/publichearingbr/annotation/synth3_gcad500/routing.md. CPU only.
"""
import csv
import json
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
from mitigation_headroom import withhold_curve  # noqa: E402

DATA = ROOT / "data" / "publichearingbr"
NAME = "synth3_gcad500"
RUN = "llama_31_8b_instruct_lc_xfitA"


def main():
    key = {r["id"]: r for r in csv.DictReader(open(DATA / "annotation" / f"{NAME}_key" / "key.csv", encoding="utf-8-sig"))}
    lab = {}
    for p in sorted((DATA / "annotation" / NAME / "raw").glob("set-*.jsonl")):
        for line in open(p, encoding="utf-8"):
            if not line.strip():
                continue
            r = json.loads(line)
            if r.get("support") in ("sustentada", "nao_sustentada"):
                lab[r["id"]] = int(r["support"] == "nao_sustentada")
    probe, nli = {}, {}
    for r in csv.DictReader(open(DATA / "probe_fresh" / "llama_31_8b_instruct" / "scores.csv", encoding="utf-8")):
        if r["variant"] == "original" and r["run"] == RUN and r["condition"] == "baseline":
            probe[(int(r["sample_id"]), r["speaker"], int(r["opinion_idx"]))] = float(r["p14"])
    for r in csv.DictReader(open(DATA / "nli_verifier" / "corruptions_llama_31_8b_instruct.csv", encoding="utf-8")):
        if r["variant"] == "original" and r["run"] == RUN and r["condition"] == "baseline":
            nli[(int(r["sample_id"]), r["speaker"], int(r["opinion_idx"]))] = -float(r["nli_ec_max"])
    y, sp, sn, sr, parts = [], [], [], [], []
    for i, k in key.items():
        if k["kind"] != "pipeline" or k["arm"] != "baseline" or int(k["replicate"]) or i not in lab:
            continue
        kk = (int(k["sample_id"]), k["speaker"], int(k["opinion_idx"]))
        y.append(lab[i]); sp.append(probe.get(kk, np.nan)); sn.append(nli.get(kk, np.nan))
        sr.append(1 - float(k["referee_containment"])); parts.append(kk[:2])
    cov_p = np.mean(~np.isnan(sp)); cov_n = np.mean(~np.isnan(sn))
    L = [f"# Routing on our own generations (Llama-3.1 baseline, {NAME})", "",
         f"{len(y)} baseline opinions judged blind, {sum(y)} unsupported; probe scores for {cov_p:.1%} of them, "
         f"NLI for {cov_n:.1%}. Generated by `scripts/routing_fresh.py`.", "",
         "| operating point | share withheld | unsupported removed | unsupported kept | supported lost | residual rate |",
         "|---|---:|---:|---:|---:|---:|"]
    withhold_curve(sr, y, "lexical referee (1 − containment)", L)
    withhold_curve(sp, y, "residual probe (L14)", L)
    withhold_curve(sn, y, "NLI cross-encoder", L)
    # participant level: share of participants whose summary, after withholding, still has >=1 unsupported opinion
    L += ["", "## Participant level: summaries that still carry an unsupported opinion after routing", "",
          "| detector | q=0 | q=0.10 | q=0.20 | q=0.30 |", "|---|---:|---:|---:|---:|"]
    y_ = np.array(y)
    for name, s in [("referee", sr), ("probe", sp), ("NLI", sn)]:
        s = np.asarray(s, float)
        cells = []
        for q in (0.0, 0.10, 0.20, 0.30):
            keep = np.ones(len(s), bool) if q == 0 else ~(s >= np.nanquantile(s, 1 - q))
            bad = {parts[j] for j in range(len(s)) if keep[j] and y_[j]}
            cells.append(f"{len(bad) / len(set(parts)):.3f} ({len(bad)})")
        L.append(f"| {name} | " + " | ".join(cells) + " |")
    text = "\n".join(L) + "\n"
    (DATA / "annotation" / NAME / "routing.md").write_text(text, encoding="utf-8")
    print(text)


if __name__ == "__main__":
    main()
