"""Loader for the RAGTruth summarization (CNN/DM) subset.

Expects RAGTruth's dataset/ directory (source_info.jsonl, response.jsonl) at
vendor/ragtruth/dataset under the repository root.
"""

import json
from dataclasses import dataclass
from pathlib import Path

DEFAULT_DATASET_DIR = Path(__file__).resolve().parents[3] / "vendor" / "ragtruth" / "dataset"


@dataclass(frozen=True)
class HallucinationSpan:
    start: int
    end: int
    text: str
    label_type: str


@dataclass(frozen=True)
class RagTruthExample:
    source_id: str
    response_id: str
    model: str
    split: str
    source_info: str
    prompt: str
    response: str
    spans: tuple[HallucinationSpan, ...]


def _load_source_info(dataset_dir: Path) -> dict[str, dict]:
    by_source_id = {}
    with open(dataset_dir / "source_info.jsonl") as f:
        for line in f:
            row = json.loads(line)
            if row["task_type"] == "Summary":
                by_source_id[row["source_id"]] = row
    return by_source_id


def load_summarization_subset(
    dataset_dir: Path = DEFAULT_DATASET_DIR,
    model: str | None = None,
) -> list[RagTruthExample]:
    """Join source_info.jsonl + response.jsonl for the Summary task type.

    Args:
        model: if given, keep only responses generated by this model
            (e.g. "llama-2-7b-chat"). RAGTruth stores responses from six
            models per source; the official train/test split lives on
            each response row, not per source.
    """
    sources = _load_source_info(dataset_dir)
    examples = []
    with open(dataset_dir / "response.jsonl") as f:
        for line in f:
            row = json.loads(line)
            source = sources.get(row["source_id"])
            if source is None:
                continue
            if model is not None and row["model"] != model:
                continue
            spans = tuple(
                HallucinationSpan(
                    start=label["start"],
                    end=label["end"],
                    text=label["text"],
                    label_type=label.get("label_type", ""),
                )
                for label in row["labels"]
            )
            examples.append(
                RagTruthExample(
                    source_id=row["source_id"],
                    response_id=row["id"],
                    model=row["model"],
                    split=row["split"],
                    source_info=source["source_info"],
                    prompt=source["prompt"],
                    response=row["response"],
                    spans=spans,
                )
            )
    return examples
